### ISSUE TITLE
middleware_1  | 2019-12-17T17:39:14.514634226+00:00 ERROR aeternal::loader - Couldn't load generation -1 from DB middleware_1  | 2019-12-17T17:39:20.537184677+00:00 ERROR aeternal::models - Error loading key block: NotFound middleware_1  | 2019-12-17T17:39:20.537286210+00:00 ERROR aeternal::loader - Couldn't load generation -1 from DB

### ISSUE THREAD

**Issue by tima-t** [aeternity/aeternal#249]
**Note: for support questions, please use the [forum](https://forum.aeternity.com)**. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ...**
  - [ ] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**

* **What is the current behavior?**

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
  
  - Node Version: v0.0.0
  - Protocol Version: 1
  - Sophia Compiler version: v0.0.0
  - Rust version: v0.00 

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. forum, telegram, etc)

**Comment by noandrea** [comment]
hello, the error is due to the node not syncing, therefore aeternal cannot find any blocks.

Everything should work correctly if you change the docker compose in a way so it connects to a external node:

```
version: '3.1'
services:
    image: aeternity/aeternal:latest
    ports:
      - "8080:80"
      - "3020:3020"
    entrypoint: ./docker/wait-for-it.sh node:3013 -- ./aeternal -p -s -w
    environment:
      - NODE_URL=ADDRESS_OF_YOUR_NODE:3013
      - AESOPHIA_URL=compiler:3080
      - DATABASE_URL=postgres://middleware:middleware@db/middleware
      - LOG_CONF=/logs/log.yaml
    volumes:
      - ${PWD}/docker/wait-for-it.sh:/app/docker/wait-for-it.sh
    depends_on:
      - db
      - node
      - compiler


  db:
    image: postgres:11
    restart: unless-stopped
    environment:
      - POSTGRES_USER=middleware
      - POSTGRES_PASSWORD=middleware
      - POSTGRES_DB=middleware
    volumes: 
      - ae-mdw-postgres-volume:/var/lib/postgresql/data
    expose: [5432]

  compiler:
    image: aeternity/aesophia_http:v4.1.0
    hostname: compiler
    expose: [3080]
    
volumes:
    ae-mdw-postgres-volume:
      external: false
    node_db:
```
